### PR TITLE
Use https by default

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This fixes mixed content issues when loading the site over https as images were getting loaded over http still.

### CODE REVIEW

**Comment by esevece** [comment]
Thank you @OmgImAlexis!

**Comment by OmgImAlexis** [comment]
Is there something else that needs to be changed for ` ` to update to use the https protocol? I assumed once this was changed it'd update the Heroku page with the new URLs.

**Comment by esevece** [comment]
Sorry, let me check. I approved the commit in my phone because I was not at home, but I haven't tried yet. I'm going to see what I'm missing.

**Comment by esevece** [comment]
@OmgImAlexis done! 
You are interested, this are the changes 242fbb7.
I noticed that the default files installed by Jekyll use `site.url` instead of `site.github.url`.

Thank you!

**Pull request merged**
